### ISSUE TITLE
Utilities.SplitMultiPolygon Bug

### ISSUE THREAD

**Issue by slayer531** [dotMorten/GeometryConversions#1]
I seem to have found a logic issue with the _SplitMultiPolygon_ method in _GeometryConversions.Shared.Utilities_.

The 1st issue that I found is that on line 19, where the ring is returned as points and IsCcw is being called. IsCcw executes as expected, but the if condition checks if the evaluation is true. In my opinion, this should be changed to 
_if (!IsCcw(ring.GetPoints()))_
                {
                    outerRings.Add(new Tuple<ReadOnlySegmentCollection, IList<ReadOnlySegmentCollection>>(ring, new List<ReadOnlySegmentCollection>()));
                }
                else
                    innerRings.Add(ring);
            }

The 2nd identified issue, is that a System.IO exception is thrown at the end of the _foreach_ loop that traverses the _innerRings_, on line 37

**Comment by dotMorten** [comment]
@slayer531 
Thanks for the report (and sorry for the slow response).
I can't make sense of the first part. Outer rings are defined by being counter clock wise, and that's what it is checking for.

**Comment by dotMorten** [comment]
I don't know what I was thinking. You're right. Fixed!
